version: "3.2"

services:
  database:
    image: mysql:8.0.16
    container_name: airportDb
    #    restart: never
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ap_db
      MYSQL_USER: ap_user
      MYSQL_PASSWORD: root
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"